apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-angular
  name: example-angular  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-angular
  template:
    metadata:
      labels:
        app: example-angular
    spec:
      containers:
        - name: deploment-container-name
          image: stephenwike/spike-deploy-angular:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80